datadir:
    /scratch/groups/wjg/kyx/NNNlib2b_Oct6/data/
fastq:
    read1:
        /scratch/groups/wjg/kyx/NNNlib2b_Oct6/data/fastq/NNNlib2b_S1_L001_R1_001.fastq
    read2:
        /scratch/groups/wjg/kyx/NNNlib2b_Oct6/data/fastq/NNNlib2b_S1_L001_R2_001.fastq
FIDfilter:
    data/reference/FID.CPfilter




